[parity]
chain = "./data/spec.json"
base_path = "data/node0"

[network]
port = 30300
discovery = true
nat = "none"
interface = "local"

[rpc]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_set", "parity_pubsub", "personal", "traces"]
port = 8540

[websockets]
port = 9540

[ipc]
disable = true

[secretstore]
disable = true

[misc]
logging = "engine=trace,miner=trace,reward=trace"
