[parity]
chain = "pos-contracts/spec.json"
base_path = "parity-data/node6"

[ui]
disable = true

[network]
port = 30306
discovery = true
reserved_peers="parity-data/reserved-peers"

[rpc]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_set", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
port = 8546

[websockets]
port = 9546

[ipc]
disable = true

[secretstore]
disable = true

[ipfs]
enable = false

[account]
unlock = ["0x522df396ae70a058bd69778408630fdb023389b2"]
password = ["config/password"]

[mining]
force_sealing = true
min_gas_price = 1000000000
engine_signer = "0x522df396ae70a058bd69778408630fdb023389b2"
reseal_on_txs = "none"
extra_data = "Parity"

[misc]
logging = "engine=trace,miner=trace,reward=trace"
