[parity]
chain = "./data/spec.json"
base_path = "data/node2"

[ui]
disable = true

[network]
port = 30302
discovery = true
reserved_peers="data/reserved-peers"
nat = "none"
interface = "local"

[rpc]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_set", "parity_pubsub", "personal", "traces", "rpc", "shh", "shh_pubsub"]
port = 8542

[websockets]
port = 9542

[ipc]
disable = true

[secretstore]
disable = true

[account]
unlock = ["0x75df42383afe6bf5194aa8fa0e9b3d5f9e869441"]
password = ["config/password"]

[mining]
force_sealing = true
min_gas_price = 1000000000
gas_floor_target = "10000000"
engine_signer = "0x75df42383afe6bf5194aa8fa0e9b3d5f9e869441"
reseal_on_txs = "none"
extra_data = "Parity"

[misc]
logging = "engine=trace,miner=trace,reward=trace"
