[parity]
chain = "./data/spec.json"
base_path = "data/node3"

[network]
port = 30303
discovery = true
reserved_peers="data/reserved-peers"
nat = "none"
interface = "local"

[rpc]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_set", "parity_pubsub", "personal", "traces"]
port = 8543

[websockets]
port = 9543

[ipc]
disable = true

[secretstore]
disable = true

[account]
unlock = ["0x522df396ae70a058bd69778408630fdb023389b2"]
password = ["config/password"]

[mining]
force_sealing = true
min_gas_price = 1000000000
gas_floor_target = "12000000"
engine_signer = "0x522df396ae70a058bd69778408630fdb023389b2"
reseal_on_txs = "none"
extra_data = "Parity"
tx_gas_limit="7500000"
tx_time_limit=1000

[misc]
logging = "engine=trace,miner=trace,reward=trace"
