[parity]
chain = "pos-contracts/spec.json"
base_path = "parity-data/node1"

[ui]
disable = true

[network]
port = 30301

[rpc]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_set", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
port = 8541

[websockets]
port = 9541

[ipc]
disable = true

[secretstore]
disable = true

[ipfs]
enable = false

[account]
unlock = ["0xbbcaa8d48289bb1ffcf9808d9aa4b1d215054c78"]
password = ["config/password"]

[mining]
force_sealing = true
min_gas_price = 1000000000
engine_signer = "0xbbcaa8d48289bb1ffcf9808d9aa4b1d215054c78"
reseal_on_txs = "none"

[misc]
logging = "engine=trace,miner=trace"
